# Generated by Django 5.2.14 on 2026-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
